# Utiliser une image de base Python
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'application dans le conteneur
COPY ../app/api /app

# Installer les dépendances
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Exposer le port de Flask
EXPOSE 5000

# Commande pour lancer l'application Flask
CMD ["python", "/app/api/main.py"]
