# Utiliser une image Python 3.12 officielle comme image de base
FROM python:3.12-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de requirements et installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code de l'application dans le conteneur
COPY app/api ./api

# Exposer le port sur lequel l'application Flask s'exécute (à ajuster si nécessaire)
EXPOSE 5000

# Définir la commande pour exécuter l'application
CMD ["python", "api/main.py"]