version: '3.8'

services:
  flask_api:
    build:
      context: ..
      dockerfile: infra/Dockerfile_api
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped