# Utiliser une image de base Python
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'application dans le conteneur
COPY ../app /app

# Installer les dépendances
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Définir une variable d'environnement pour le fichier de token
ENV DISCORD_BOT_TOKEN_FILE=/app/discordBot/api_token/token.txt

# Script pour démarrer le bot en lisant le token depuis le fichier
CMD ["sh", "-c", "python /app/discordBot/bot.py"]